apiVersion: v2
appVersion: demo-shop-v0.0.5
description: A Helm chart for restorecommerce data importer
home: https://github.com/restorecommerce/data
icon: https://avatars0.githubusercontent.com/u/8339525
maintainers:
- email: info@restorecommerce.io
  name: restorecommerce
  url: https://restorecommerce.io/
name: data-import
sources:
- https://github.com/restorecommerce/data
type: application
version: 0.1.11
