helm-extra-args: --timeout 600
check-version-increment: true
debug: true
lint-conf: ./chart-testing/lintconf.yaml
chart-yaml-schema: ./chart-testing/chart_schema.yaml
chart-dirs:
  - charts
chart-repos:
  - elastic=https://helm.elastic.co
  - kube-arangodb=https://arangodb.github.io/kube-arangodb
