[project]
name = "charts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.2",
    "python-dxf>=11.4.0",
    "semver>=3.0.2",
    "yamale>=5.0.0",
]
