apiVersion: v2
dependencies:
- name: identity-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.15
- name: notification-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.14
- name: access-control-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.13
- name: ostorage-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.14
- name: scheduling-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.16
- name: rendering-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.15
- name: pdf-rendering-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.10
- name: fulfillment-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.6
- name: indexing-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.7
- name: catalog-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.9
- name: invoicing-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.9
- name: ordering-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.6
- name: payment-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.8
- name: resource-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.8
- name: facade-srv
  repository: https://restorecommerce.github.io/charts/
  version: 0.1.14
- name: cloudserver
  version: 1.0.4
- name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: 21.4.0
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.8.4
description: A Helm chart for the Restorecommerce system
home: https://github.com/restorecommerce/system
icon: https://avatars0.githubusercontent.com/u/8339525
maintainers:
- email: info@restorecommerce.io
  name: restorecommerce
  url: https://restorecommerce.io/
name: system
type: application
version: 0.1.15
