accessMode: ReadWriteOnce

jobs:
  migrations:
    enabled: true
    activeDeadlineSeconds: 3600
    backoffLimit: 6
    image:
      pullSecrets: []
      pullPolicy: IfNotPresent
      repository: busybox
      tag: latest
    resources:
      requests:
        cpu: 250m
        memory: 200Mi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
  dataImport:
    enabled: true
    activeDeadlineSeconds: 3600
    backoffLimit: 6
    image:
      pullSecrets: []
      pullPolicy: IfNotPresent
      repository: restorecommerce/data
      tag: demo-shop-v0.0.5
    resources:
      requests:
        cpu: 250m
        memory: 200Mi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    apiKey: FACADE_API_KEY
    endpoint:
      host: facade-srv
      port: 5000

identity-srv:
  fullnameOverride: identity-srv
  env:
    extras:
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: redis__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: authorization__enabled
        value: "false"
      - name: database__main__host
        value: arangodb-single-000000
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

notification-srv:
  fullnameOverride: notification-srv
  env:
    extras:
      - name: redis__url
        value: redis://redis:6379
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

access-control-srv:
  fullnameOverride: access-control-srv
  env:
    extras:
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: redis__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: authorization__enabled
        value: "false"
      - name: database__main__host
        value: arangodb-single-000000
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

ostorage-srv:
  fullnameOverride: ostorage-srv
  env:
    extras:
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: redis__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: s3__client__accessKeyId
        value: ZFKQGYD2P6DJO4U7N33U
      - name: s3__client__secretAccessKey
        value: fO09epo9zT6tslwhh192l0UHbtpCjCYTnE3TYtec
      - name: s3__client__endpoint
        value: http://cloudserver:8000
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

scheduling-srv:
  fullnameOverride: scheduling-srv
  env:
    extras:
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: redis__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

rendering-srv:
  fullnameOverride: rendering-srv
  env:
    extras:
      - name: redis__url
        value: redis://redis:6379
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

pdf-rendering-srv:
  fullnameOverride: pdf-rendering-srv

fulfillment-srv:
  fullnameOverride: fulfillment-srv
  env:
    extras:
      - name: redis__url
        value: redis://redis:6379
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: database__main__host
        value: arangodb-single-000000
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

catalog-srv:
  fullnameOverride: catalog-srv
  env:
    extras:
      - name: redis__url
        value: redis://redis:6379
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: database__main__host
        value: arangodb-single-000000
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

invoicing-srv:
  fullnameOverride: invoicing-srv
  env:
    extras:
      - name: redis__url
        value: redis://redis:6379
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: database__main__host
        value: arangodb-single-000000
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

ordering-srv:
  fullnameOverride: ordering-srv
  env:
    extras:
      - name: redis__url
        value: redis://redis:6379
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: database__main__host
        value: arangodb-single-000000
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

payment-srv:
  enabled: false
  fullnameOverride: payment-srv
  env:
    extras:
      - name: redis__host
        value: redis://redis:6379
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

resource-srv:
  fullnameOverride: resource-srv
  env:
    extras:
      - name: redis__url
        value: redis://redis:6379
      - name: authorization__cache__url
        value: redis://redis:6379
      - name: logger__elasticsearch__clientOpts__node
        value: http://restorecommerce-es-http:9200
      - name: authorization__enabled
        value: "false"
      - name: database__main__host
        value: arangodb-single-000000
      - name: events__kafka__kafka__brokers
        value: '["kafka-kafka-bootstrap:9092"]'

facade-srv:
  fullnameOverride: facade-srv

cloudserver:
  fullnameOverride: cloudserver
  image:
    repository: ghcr.io/scality/cloudserver
    tag: 9.0.30
    pullPolicy: IfNotPresent
  api:
    replicaCount: 1
    credentials:
      accessKey: ZFKQGYD2P6DJO4U7N33U
      secretKey: fO09epo9zT6tslwhh192l0UHbtpCjCYTnE3TYtec
    logLevel: info
    endpoint: cloudserver
  persistence:
    size: 10Gi
    accessMode: ReadWriteMany
  resources:
    requests:
      memory: 250Mi
    limits:
      memory: 512Mi

redis:
  fullnameOverride: redis
  auth:
    enabled: false
  architecture: standalone
  resources:
    limits:
      memory: 256Mi
