jobs:
  migrations:
    enabled: true
    activeDeadlineSeconds: 3600
    backoffLimit: 6
    image:
      pullSecrets: []
      pullPolicy: IfNotPresent
      repository: busybox
      tag: latest
    resources:
      requests:
        cpu: 250m
        memory: 200Mi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
  dataImport:
    enabled: true
    activeDeadlineSeconds: 3600
    backoffLimit: 6
    image:
      pullSecrets: []
      pullPolicy: IfNotPresent
      repository: restorecommerce/data
      tag: demo-shop-v0.0.4
    resources:
      requests:
        cpu: 250m
        memory: 200Mi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    apiKey: FACADE_API_KEY
    endpoint:
      host: facade-srv
      port: 5000

identity-srv:
  fullnameOverride: identity-srv
  env:
    extras:
      - name: authorization__cache__host
        value: redis-master
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200
      - name: authorization__enabled
        value: "false"

notification-srv:
  fullnameOverride: notification-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200

access-control-srv:
  fullnameOverride: access-control-srv
  env:
    extras:
      - name: authorization__cache__host
        value: redis-master
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200
      - name: authorization__enabled
        value: "false"

ostorage-srv:
  fullnameOverride: ostorage-srv
  env:
    extras:
      - name: authorization__cache__host
        value: redis-master
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200
      - name: s3__client__accessKeyId
        value: REPLACE_ME_ACCESS
      - name: s3__client__secretAccessKey
        value: REPLACE_ME_SECRET

scheduling-srv:
  fullnameOverride: scheduling-srv
  env:
    extras:
      - name: authorization__cache__host
        value: redis-master
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200

rendering-srv:
  fullnameOverride: rendering-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200

pdf-rendering-srv:
  fullnameOverride: pdf-rendering-srv

fulfillment-srv:
  fullnameOverride: fulfillment-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200

indexing-srv:
  fullnameOverride: indexing-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200
      - name: elasticsearch__client__node
        value: http://elasticsearch-master:9200

catalog-srv:
  fullnameOverride: catalog-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200

invoicing-srv:
  fullnameOverride: invoicing-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200

ordering-srv:
  fullnameOverride: ordering-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200

payment-srv:
  fullnameOverride: payment-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200

resource-srv:
  fullnameOverride: resource-srv
  env:
    extras:
      - name: redis__host
        value: redis-master
      - name: authorization__cache__host
        value: redis-master
      - name: logger__elasticsearch__clientOpts__node
        value: http://elasticsearch-master:9200
      - name: authorization__enabled
        value: "false"

facade-srv:
  fullnameOverride: facade-srv

zookeeper:
  fullnameOverride: zookeeper

minio:
  fullnameOverride: minio
  accessKey: REPLACE_ME_ACCESS
  secretKey: REPLACE_ME_SECRET
  persistence:
    size: 10Gi

kafka:
  fullnameOverride: kafka
  zookeeper:
    enabled: false
  externalZookeeper:
    servers:
      - "zookeeper:2181"
  deleteTopicEnable: true
  autoCreateTopicsEnable: true

kafka-manager:
  fullnameOverride: kafka-manager
  zkHosts: "zookeeper:2181"
  applicationSecret: "REPLACE_ME"
  basicAuth:
    password: "REPLACE_ME"
    ldap:
      password: "REPLACE_ME"

redis:
  fullnameOverride: redis
  usePassword: false

elasticsearch:
  antiAffinity: "soft"
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 10Gi
  replicas: 2

kibana:
  fullnameOverride: kibana
  elasticsearchHosts: "http://elasticsearch-master:9200"
