apiVersion: v2
name: notification-srv
description: A Helm chart for restorecommerce notification-srv
type: application
version: 0.1.0
appVersion: 0.1.2
icon: https://avatars0.githubusercontent.com/u/8339525
home: https://docs.restorecommerce.io/notification-srv/index.html
sources:
  - https://github.com/restorecommerce/notification-srv