{{- if .Values.seedAccounts }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "identity-srv.fullname" . }}-seed-accounts"
  labels:
    {{- include "identity-srv.labels" . | nindent 4 }}
stringData:
  seed-accounts.json: {{ .Values.seedAccounts | quote }}
{{- end }}