{{- if .Values.seedRoles }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "identity-srv.fullname" . }}-seed-roles"
  labels:
    {{- include "identity-srv.labels" . | nindent 4 }}
stringData:
  seed-roles.json: {{ tpl (.Values.seedRoles | quote) . }}
{{- end }}