apiVersion: v2
appVersion: 0.2.9
description: Restorecommerce fulfillment-srv
home: https://docs.restorecommerce.io/fulfillment-srv/index.html
icon: https://avatars0.githubusercontent.com/u/8339525
maintainers:
- email: info@restorecommerce.io
  name: restorecommerce
  url: https://restorecommerce.io/
name: fulfillment-srv
sources:
- https://github.com/restorecommerce/fulfillment-srv
type: application
version: 0.1.24
