apiVersion: v2
appVersion: 1.3.7
description: Restorecommerce rendering-srv
home: https://docs.restorecommerce.io/rendering-srv/index.html
icon: https://avatars0.githubusercontent.com/u/8339525
maintainers:
- email: info@restorecommerce.io
  name: restorecommerce
  url: https://restorecommerce.io/
name: rendering-srv
sources:
- https://github.com/restorecommerce/rendering-srv
type: application
version: 0.1.25
