{{- if (ne .Values.global.authorization.apiKey "") }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "notification-srv.fullname" . }}-api-key"
stringData:
  authorization__apiKey: {{ .Values.global.authorization.apiKey }}
{{- end }}