apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "rendering-srv.fullname" . }}-handlebars"
  labels:
    {{- include "rendering-srv.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.handlebars | nindent 2 }}