kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloudserver
spec:
  accessModes:
    - {{ .Values.pvcAccessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
