apiVersion: v1
kind: Service
metadata:
  name: cloudserver
spec:
  type: ClusterIP
  ports:
    - name: s3
      port: 8000
      protocol: TCP
      targetPort: s3
    - name: localdata
      port: 9991
      protocol: TCP
      targetPort: localdata
    - name: localmetadata
      port: 9990
      protocol: TCP
      targetPort: localmetadata
  selector:
    app: cloudserver
