{{- if .Values.config.literal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "access-control-srv.fullname" . }}-config"
  labels:
    {{- include "access-control-srv.labels" . | nindent 4 }}
data:
  config_production_override.json: {{ .Values.config.literal | quote }}
{{- end }}