{{- if .Values.seedPolicies }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "identity-srv.fullname" . }}-seed-policies"
  labels:
    {{- include "identity-srv.labels" . | nindent 4 }}
stringData:
  seed-accounts.json: {{ .Values.seedPolicies | quote }}
{{- end }}