{{- if .Values.seedRules }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "access-control-srv.fullname" . }}-seed-rules"
  labels:
    {{- include "access-control-srv.labels" . | nindent 4 }}
stringData:
  seed-accounts.json: {{ tpl (.Values.seedRules | quote) . }}
{{- end }}