{{- if .Values.seedPolicies }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "access-control-srv.fullname" . }}-seed-policies"
  labels:
    {{- include "access-control-srv.labels" . | nindent 4 }}
stringData:
  seed-accounts.json: {{ tpl (.Values.seedPolicies | quote) . }}
{{- end }}