{{- if .Values.seedRules }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "identity-srv.fullname" . }}-seed-rules"
  labels:
    {{- include "identity-srv.labels" . | nindent 4 }}
stringData:
  seed-accounts.json: {{ .Values.seedRules | quote }}
{{- end }}