{{- if .Values.seedPolicySets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "access-control-srv.fullname" . }}-seed-policysets"
  labels:
    {{- include "access-control-srv.labels" . | nindent 4 }}
stringData:
  seed-accounts.json: {{ tpl (.Values.seedPolicySets | quote) . }}
{{- end }}