apiVersion: v2
name: ordering-srv
description: Restorecommerce ordering-srv
type: application
version: 0.1.5
appVersion: 0.0.4
icon: https://avatars0.githubusercontent.com/u/8339525
home: https://docs.restorecommerce.io/ordering-srv/index.html
sources:
  - https://github.com/restorecommerce/ordering-srv
maintainers:
  - name: restorecommerce
    url: https://restorecommerce.io/
    email: info@restorecommerce.io
