{{- if .Values.jobs.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "system.fullname" . }}-1-migrations
  labels:
    {{- include "system.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  activeDeadlineSeconds: {{ .Values.jobs.migrations.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.jobs.migrations.backoffLimit }}

  template:
    metadata:
      labels:
        {{- include "system.labels" . | nindent 8 }}
    spec:
      {{- if .Values.jobs.migrations.tolerations }}
      tolerations:
        {{- toYaml .Values.jobs.migrations.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.jobs.migrations.securityContext.runAsUser }}
        fsGroup: {{ .Values.jobs.migrations.securityContext.fsGroup }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "system.fullname" . }}-1-migrations
      initContainers:
        # TODO Wait for all services
        - name: wait-for-facade
          image: groundnuty/k8s-wait-for:v1.7
          imagePullPolicy: IfNotPresent
          args:
            - "service"
            - "facade-srv"
        - name: wait-for-identity
          image: groundnuty/k8s-wait-for:v1.7
          imagePullPolicy: IfNotPresent
          args:
            - "service"
            - "identity-srv"
        - name: wait-for-resource
          image: groundnuty/k8s-wait-for:v1.7
          imagePullPolicy: IfNotPresent
          args:
            - "service"
            - "resource-srv"
        - name: wait-for-access-control
          image: groundnuty/k8s-wait-for:v1.7
          imagePullPolicy: IfNotPresent
          args:
            - "service"
            - "access-control-srv"
      containers:
        - name: migrations
          image: "{{ .Values.jobs.migrations.image.repository }}:{{ .Values.jobs.migrations.image.tag }}"
          args:
            - echo
            - hello
          resources:
            {{- toYaml .Values.jobs.migrations.resources | nindent 12 }}
    {{- if .Values.jobs.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.jobs.migrations.nodeSelector | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "system.fullname" . }}-1-migrations
  labels:
    {{- include "system.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "system.fullname" . }}-1-migrations
  labels:
    {{- include "system.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "system.fullname" . }}-1-migrations
  labels:
    {{- include "system.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "system.fullname" . }}-1-migrations
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "system.fullname" . }}-1-migrations
{{- end }}
