{{- if .Values.jobs.dataImport.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "system.fullname" . }}-2-data-import
  labels:
    {{- include "system.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  activeDeadlineSeconds: {{ .Values.jobs.dataImport.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.jobs.dataImport.backoffLimit }}

  template:
    metadata:
      labels:
        {{- include "system.labels" . | nindent 8 }}
    spec:
      {{- if .Values.jobs.dataImport.tolerations }}
      tolerations:
        {{- toYaml .Values.jobs.dataImport.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.jobs.dataImport.securityContext.runAsUser }}
        fsGroup: {{ .Values.jobs.dataImport.securityContext.fsGroup }}
      restartPolicy: OnFailure
      initContainers:
        # TODO Wait for all services
        - name: wait-for-facade
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "service"
            - "facade-srv"
        - name: wait-for-identity
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "service"
            - "identity-srv"
        - name: wait-for-resource
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "service"
            - "resource-srv"
        - name: wait-for-access-control
          image: groundnuty/k8s-wait-for:v1.3
          imagePullPolicy: Always
          args:
            - "service"
            - "access-control-srv"
      containers:
        - name: data-import
          image: "{{ .Values.jobs.dataImport.image.repository }}:{{ .Values.jobs.dataImport.image.tag }}"
          args:
            - "import"
            - "-t"
            - {{ .Values.jobs.dataImport.apiKey }}
            - "-h"
            - {{ .Values.jobs.dataImport.endpoint.host }}
            - "-p"
            - {{ .Values.jobs.dataImport.endpoint.port | quote }}
            - "-j"
            - "master"
            - "-j"
            - "identity"
            - "-j"
            - "extra"
          resources:
            {{- toYaml .Values.jobs.dataImport.resources | nindent 12 }}
    {{- if .Values.jobs.dataImport.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.jobs.migrations.nodeSelector | nindent 8 }}
    {{- end }}
{{- end }}