apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: restorecommerce
spec:
  version: 7.9.2
  count: 1
  elasticsearchRef:
    name: restorecommerce
  config:
    xpack.security.enabled: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 4Gi
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
