{{- if (ne .Values.global.authentication.apiKey "") }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "scheduling-srv.fullname" . }}-api-key"
stringData:
  authentication__apiKey: {{ .Values.global.authentication.apiKey }}
{{- end }}