apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduling-srv.fullname" . }}
  labels:
    {{- include "scheduling-srv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.extraPorts.service }}
    {{- toYaml .Values.extraPorts.service | nindent 4 }}
    {{- end }}
  selector:
    {{- include "scheduling-srv.selectorLabels" . | nindent 4 }}
