apiVersion: v2
name: catalog-srv
description: A Helm chart for restorecommerce catalog-srv
type: application
version: 0.1.2
appVersion: 0.0.4
icon: https://avatars0.githubusercontent.com/u/8339525
home: https://docs.restorecommerce.io/catalog-srv/index.html
sources:
  - https://github.com/restorecommerce/catalog-srv
maintainers:
  - name: restorecommerce
    url: https://restorecommerce.io/
    email: info@restorecommerce.io
