apiVersion: v2
appVersion: 1.5.2
description: Restorecommerce catalog-srv
home: https://docs.restorecommerce.io/catalog-srv/index.html
icon: https://avatars0.githubusercontent.com/u/8339525
maintainers:
- email: info@restorecommerce.io
  name: restorecommerce
  url: https://restorecommerce.io/
name: catalog-srv
sources:
- https://github.com/restorecommerce/catalog-srv
type: application
version: 0.1.27
