apiVersion: v2
name: pdf-rendering-srv
description: A Helm chart for restorecommerce pdf-rendering-srv
type: application
version: 0.1.2
appVersion: 0.1.0
icon: https://avatars0.githubusercontent.com/u/8339525
home: https://docs.restorecommerce.io/pdf-rendering-srv/index.html
sources:
  - https://github.com/restorecommerce/pdf-rendering-srv
maintainers:
  - name: restorecommerce
    url: https://restorecommerce.io/
    email: info@restorecommerce.io
