apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payment-srv.fullname" . }}
  labels:
    {{- include "payment-srv.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "payment-srv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if (ne .Values.global.authentication.apiKey "") }}
        checksum/apisecret: {{ include (print $.Template.BasePath "/api-key-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "payment-srv.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "payment-srv.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          env:
            - name: npm_config_cache
              value: /tmp/npm/
            - name: NODE_ENV
              value: {{ include "payment-srv.nodeEnv" . }}
            {{- if (ne .Values.global.authentication.apiKey "") }}
            - name: authentication__apiKey
              valueFrom:
                secretKeyRef:
                  name: "{{ include "payment-srv.fullname" . }}-api-key"
                  key: authentication__apiKey
            {{- end }}
            {{- if .Values.env.extras }}
            {{- toYaml .Values.env.extras | nindent 12 }}
            {{- end }}
          {{- if .Values.enableHealthCheck }}
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 30
            grpc:
              port: 50051
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            grpc:
              port: 50051
              service: readiness
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- if or .Values.config.name .Values.config.literal }}
            - name: config
              mountPath: "/home/node/payment-srv/cfg/config_{{ .Values.env.nodeEnv }}_override.json"
              subPath: {{ .Values.config.file | quote }}
          {{- end }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- if or .Values.config.name .Values.config.literal }}
        - name: config
          configMap:
            {{- with .Values.config.name }}
            name: {{ . | quote }}
            {{- end }}
            {{- if .Values.config.literal }}
            name: "{{ include "payment-srv.fullname" . }}-config"
            {{- end }}
      {{- end }}
