name: integration

on: workflow_dispatch
  # push:
  #   paths:
  #     - ".github/workflows/integration.yaml"
  #     - "charts/system/**/*"
  # pull_request:
  #   paths:
  #     - ".github/workflows/integration.yaml"
  #     - "charts/system/**/*"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - v1.31.0
          - v1.32.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: medyagh/setup-minikube@latest
        with:
          container-runtime: containerd
          kubernetes-version: ${{ matrix.k8s }}
          cni: cilium
          addons: volumesnapshots,csi-hostpath-driver,storage-provisioner,default-storageclass

      - name: Install dependencies
        run: |
          helm install arangodb-crd https://github.com/arangodb/kube-arangodb/releases/download/1.3.1/kube-arangodb-crd-1.3.1.tgz
          helm install --create-namespace -n restorecommerce arangodb-operator https://github.com/arangodb/kube-arangodb/releases/download/1.3.1/kube-arangodb-1.3.1.tgz

          helm repo add elastic https://helm.elastic.co
          helm repo update
          helm install --create-namespace -n restorecommerce elastic-operator elastic/eck-operator --version 3.1.0

      - name: Install system chart
        run: helm install -n restorecommerce --timeout 30m0s --wait restorecommerce ./charts/system

      - name: View pods
        run: kubectl -n restorecommerce get pods
