name: Upgrade Services Charts

on:
  repository_dispatch:
    types: [upgrade-services]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add helm repos
        run: .github/add-repos.sh

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Bump chart versions
        run: python upgrade.py

      - name: Debug
        run: git diff
