helmDefaults:
  wait: true
  createNamespace: true
  timeout: 1200

environments:
  default:
    values:
      - cloudserver:
          accessKey: REPLACE_ME_ACCESS
          secretKey: REPLACE_ME_SECRET

repositories:
  - name: restorecommerce
    url: https://restorecommerce.github.io/helm/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: elastic
    url: https://helm.elastic.co
  - name: stable
    url: https://charts.helm.sh/stable

# Deploy after initial to wait for CRD's to deploy
helmfiles:
  - path: arangodb-crd-helmfile.yaml

releases:
  - name: identity-srv
    namespace: restorecommerce
    chart: ../../charts/identity-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: authorization__cache__host
              value: redis-master
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: notification-srv
    namespace: restorecommerce
    chart: ../../charts/notification-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: access-control-srv
    namespace: restorecommerce
    chart: ../../charts/access-control-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: authorization__cache__host
              value: redis-master
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: ostorage-srv
    namespace: restorecommerce
    chart: ../../charts/ostorage-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: authorization__cache__host
              value: redis-master
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200
            - name: s3__client__accessKeyId
              value: {{ .Values.cloudserver.accessKey }}
            - name: s3__client__secretAccessKey
              value: {{ .Values.cloudserver.secretKey }}

  - name: scheduling-srv
    namespace: restorecommerce
    chart: ../../charts/scheduling-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: authorization__cache__host
              value: redis-master
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: rendering-srv
    namespace: restorecommerce
    chart: ../../charts/rendering-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: pdf-rendering-srv
    namespace: restorecommerce
    chart: ../../charts/pdf-rendering-srv
    installed: true
    atomic: true
    cleanupOnFail: true

  - name: fulfillment-srv
    namespace: restorecommerce
    chart: ../../charts/fulfillment-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: indexing-srv
    namespace: restorecommerce
    chart: ../../charts/indexing-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200
            - name: elasticsearch__client__node
              value: http://elasticsearch-master:9200

  - name: catalog-srv
    namespace: restorecommerce
    chart: ../../charts/catalog-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: invoicing-srv
    namespace: restorecommerce
    chart: ../../charts/invoicing-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: ordering-srv
    namespace: restorecommerce
    chart: ../../charts/ordering-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: payment-srv
    namespace: restorecommerce
    chart: ../../charts/payment-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: resource-srv
    namespace: restorecommerce
    chart: ../../charts/resource-srv
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - env:
          extras:
            - name: redis__host
              value: redis-master
            - name: authorization__cache__host
              value: redis-master
            - name: logger__elasticsearch__clientOpts__node
              value: http://elasticsearch-master:9200

  - name: facade-srv
    namespace: restorecommerce
    chart: ../../charts/facade-srv
    installed: true
    atomic: true
    cleanupOnFail: true

  - name: cloudserver
    namespace: restorecommerce
    chart: ../../charts/system/charts/cloudserver
    version: 1.0.4
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - accessKey: {{ .Values.cloudserver.accessKey }}
        secretKey: {{ .Values.cloudserver.secretKey }}
        persistence:
          size: 10Gi

  - name: kafka
    namespace: restorecommerce
    chart: bitnami/kafka
    version: 11.8.7
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - zookeeper:
          enabled: false
        externalZookeeper:
          servers:
            - "zookeeper:2181"
        deleteTopicEnable: true
        autoCreateTopicsEnable: true

  - name: redis
    namespace: restorecommerce
    chart: bitnami/redis
    version: 11.2.1
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - usePassword: false

  - name: elasticsearch
    namespace: restorecommerce
    chart: elastic/elasticsearch
    version: 7.9.2
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - antiAffinity: "soft"
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
        replicas: 1

  - name: kibana
    namespace: restorecommerce
    chart: elastic/kibana
    version: 7.9.2
    installed: true
    atomic: true
    cleanupOnFail: true
    values:
      - fullnameOverride: kibana
        elasticsearchHosts: "http://elasticsearch-master:9200"

  - name: arangodb
    namespace: restorecommerce
    chart: https://github.com/arangodb/kube-arangodb/releases/download/1.1.5/kube-arangodb-1.1.5.tgz
    installed: true
    atomic: true
    cleanupOnFail: true

  - name: arangodb-deployments
    namespace: restorecommerce
    chart: ./arangodb
    installed: true
    atomic: true
    cleanupOnFail: true